### ISSUE TITLE
header title does not work

### ISSUE THREAD

**Issue by alixcan** [Owen-oj/laravel-gentelella#1]
Hi,

Thanks for package but in header partial `@yield('title')` not working returns empty.

**Comment by Owen-oj** [comment]
Thanks for reaching out.
You would have to do this on all your pages `@section('title',your-page-name')`

**Comment by alixcan** [comment]
Uh. I'm sorry while i look at the views, dashboard.blade.php file has title, but home.blade.php does'nt
and when you loged in you redirected to the dashboard page so i consume it was a problem about @inlude partials :)

For give me,
Thanks for your attention. have a greate day.
